/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package productinventory;

/**
 *
 * @author WINDOWS 10
 */

import java.awt.event.KeyEvent;
import java.sql.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class SalesReportJFrame extends javax.swing.JFrame {

    /**
     * Creates new form SalesReportJFrame
     */
    public SalesReportJFrame() {
        initComponents();
        Connect();
        Fetch();
    }

    Connection connection;
    PreparedStatement preparedStatement;
    ResultSet resultSet;

    public void Connect() {
        if (connection == null) {
            try {
                String url = "jdbc:mysql://localhost:3306/dbinventory";
                String user = "root";
                String password = "";
                DriverManager.registerDriver(new com.mysql.jdbc.Driver());
                connection = DriverManager.getConnection(url, user, password);
            } catch (SQLException t) {
                System.out.println("Error connection!");
            }
        }
    }

    public void Fetch() {
        try {
            int q;
            preparedStatement = connection.prepareStatement("SELECT `sales_product_tbl`.`sales_id`, `sales_tbl`.`date`, `sales_product_tbl`.`product_id`, `product_tbl`.`product_name`, `sales_product_tbl`.`product_retail_price`, `sales_product_tbl`.`quantity`, `sales_product_tbl`.`total`\n"
                    + "FROM `sales_product_tbl` \n"
                    + "	LEFT JOIN `sales_tbl` ON `sales_product_tbl`.`sales_id` = `sales_tbl`.`sales_id` \n"
                    + "	LEFT JOIN `product_tbl` ON `sales_product_tbl`.`product_id` = `product_tbl`.`product_id`;");
            resultSet = preparedStatement.executeQuery();
            ResultSetMetaData rss = resultSet.getMetaData();
            q = rss.getColumnCount();

            DefaultTableModel defaultTable = (DefaultTableModel) salesJTable.getModel();
            defaultTable.setRowCount(0);
            while (resultSet.next()) {
                Vector vector = new Vector();
                for (int a = 1; a <= q; a++) {
                    vector.add(resultSet.getString("sales_id"));
                    vector.add(resultSet.getString("date"));
                    vector.add(resultSet.getString("product_id"));
                    vector.add(resultSet.getString("product_name"));
                    vector.add(resultSet.getString("product_retail_price"));
                    vector.add(resultSet.getString("quantity"));
                    vector.add(resultSet.getString("total"));
                }
                defaultTable.addRow(vector);
            }

            int sumPrice = 0;

            for (int i = 0; i < salesJTable.getRowCount(); i++) {
                sumPrice += Integer.parseInt(salesJTable.getValueAt(i, 6).toString());
            }

            totalCostJTextField.setText(String.valueOf(sumPrice));

            int sumQuantity = 0;

            for (int i = 0; i < salesJTable.getRowCount(); i++) {
                sumQuantity += Integer.parseInt(salesJTable.getValueAt(i, 5).toString());
            }

            totalQuantityJTextField.setText(String.valueOf(sumQuantity));
        } catch (SQLException ex) {
            Logger.getLogger(ProductJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salesReportJLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        salesJTable = new javax.swing.JTable();
        totalCostJTextField = new javax.swing.JTextField();
        totalCostJLabel = new javax.swing.JLabel();
        totalQuantityProductSalesJLabel = new javax.swing.JLabel();
        totalQuantityJTextField = new javax.swing.JTextField();
        closeJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        salesReportJLabel.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        salesReportJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salesReportJLabel.setText("SALES REPORT");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        salesJTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        salesJTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        salesJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sales ID", "Date", "Product ID", "Product Name", "Price", "Quantity", "Total"
            }
        ));
        jScrollPane1.setViewportView(salesJTable);

        totalCostJLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        totalCostJLabel.setText("Total Sales");

        totalQuantityProductSalesJLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        totalQuantityProductSalesJLabel.setText("Total Quantity Product Sales");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(totalQuantityProductSalesJLabel)
                            .addComponent(totalCostJLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalCostJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalQuantityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalQuantityProductSalesJLabel)
                    .addComponent(totalQuantityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalCostJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalCostJLabel))
                .addContainerGap(14, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        closeJButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        closeJButton.setText("CLOSE");
        closeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salesReportJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(closeJButton)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(salesReportJLabel)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(closeJButton)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeJButtonActionPerformed
        // TODO add your handling code here:
        new SalesJFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_closeJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesReportJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesReportJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesReportJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesReportJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeJButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable salesJTable;
    private javax.swing.JLabel salesReportJLabel;
    private javax.swing.JLabel totalCostJLabel;
    private javax.swing.JTextField totalCostJTextField;
    private javax.swing.JTextField totalQuantityJTextField;
    private javax.swing.JLabel totalQuantityProductSalesJLabel;
    // End of variables declaration//GEN-END:variables
}
